export default {
  VITE_API_ORIGIN: import.meta.env.VITE_API_ORIGIN,
  VITE_COPYRIGHT_YEAR: import.meta.env.VITE_COPYRIGHT_YEAR,
  VITE_EXTENSION_STORE_URL_CHROME: import.meta.env
    .VITE_EXTENSION_STORE_URL_CHROME,
  VITE_EXTENSION_STORE_URL_EDGE: import.meta.env.VITE_EXTENSION_STORE_URL_EDGE,
  VITE_EXTENSION_STORE_URL_FIREFOX: import.meta.env
    .VITE_EXTENSION_STORE_URL_FIREFOX,
  VITE_RECAPTCHA_SITE_KEY: import.meta.env.VITE_RECAPTCHA_SITE_KEY,
  VITE_SSM_WEBAPP_ORIGIN: import.meta.env.VITE_SSM_WEBAPP_ORIGIN,
};
