export default {
  VITE_API_ORIGIN: import.meta.env.VITE_API_ORIGIN,
  VITE_SSM_USER_POOL_HOSTED_UI_QUERY: import.meta.env
    .VITE_SSM_USER_POOL_HOSTED_UI_QUERY,
  VITE_SSM_USER_POOL_CLIENT_ID: import.meta.env.VITE_SSM_USER_POOL_CLIENT_ID,
  VITE_SSM_USER_POOL_CUSTOM_DOMAIN: import.meta.env
    .VITE_SSM_USER_POOL_CUSTOM_DOMAIN,
  VITE_SSM_USER_POOL_PROVIDER_URL: import.meta.env
    .VITE_SSM_USER_POOL_PROVIDER_URL,
  VITE_SSM_USER_POOL_ID: import.meta.env.VITE_SSM_USER_POOL_ID,
  VITE_SSM_USER_POOL_OAUTH_REDIRECT_SIGN_IN: import.meta.env
    .VITE_SSM_USER_POOL_OAUTH_REDIRECT_SIGN_IN,
  VITE_SSM_USER_POOL_OAUTH_REDIRECT_SIGN_OUT: import.meta.env
    .VITE_SSM_USER_POOL_OAUTH_REDIRECT_SIGN_OUT,
  VITE_SSM_USER_POOL_OAUTH_RESPONSE_TYPE: import.meta.env
    .VITE_SSM_USER_POOL_OAUTH_RESPONSE_TYPE,
  VITE_SSM_USER_POOL_OAUTH_SCOPES:
    import.meta.env.VITE_SSM_USER_POOL_OAUTH_SCOPES.split(","),
  VITE_SSM_WEBAPP_ORIGIN: import.meta.env.VITE_SSM_WEBAPP_ORIGIN,
};
