name: Run all tests
run-name:
  "${{ github.workflow }} - Environment: ${{ inputs.environment || 'test' }}"

on:
  pull_request:
    paths:
      - packages/**
  workflow_dispatch:
    inputs:
      environment:
        default: test
        description: "Which .env config to use"
        required: true
        type: choice
        options:
          - development
          - production
          - test

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VITE_MODE: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn install
      - run: yarn test
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          project: packages/popup
          start: yarn workspace @worm/popup dev
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: packages/popup/cypress/screenshots
