name: Run all tests

on:
  pull_request:
    paths:
      - packages/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn install
      - run: yarn test
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          project: packages/popup
          start: yarn workspace @worm/popup dev
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: packages/popup/cypress/screenshots
