name: Run all tests
run-name: "${{ github.workflow }} - Mode: test"

on:
  pull_request:
    paths:
      - .github/workflows/run-tests.yml
      - packages/**

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      VITE_MODE: test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install

      - name: Run Jest tests
        id: jest
        run: yarn test:jest --json --outputFile=jest-results.json

      - name: Generate Jest report
        run: yarn tsx .github/scripts/test-reporter.ts jest-results.json
        if: always()

      - name: Run Popup Cypress tests
        uses: cypress-io/github-action@v6
        id: popup-cypress
        with:
          browser: chrome
          project: packages/popup
          start: yarn workspace @worm/popup dev

      - name: Upload Popup Cypress failures
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: popup-cypress-screenshots
          path: packages/popup/cypress/screenshots

      - name: Run Shared Cypress tests
        uses: cypress-io/github-action@v6
        id: shared-cypress
        with:
          browser: chrome
          project: packages/shared

      - name: Upload Shared Cypress failures
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: shared-cypress-screenshots
          path: packages/shared/cypress/screenshots
